// AUTO-GENERATED by scripts/build-mined-library.ts — do not edit by hand.
// Complete tune packages mined from folk MIDI (GPL-3.0). Regenerate with:
//   npm run mine-melodies -- scripts/midi --out scripts/mined-all.json
//   npx tsx scripts/build-mined-library.ts

import type { TunePackage } from "./tune-packages";

export const MINED_TUNE_PACKAGES: TunePackage[] = [
  {
    "id": "mellow-jigs100",
    "mood": "jazzy",
    "source": "mined",
    "phrases": {
      "A": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 4,
            "beats": 0.75,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 7,
            "beats": 0.25,
            "vel": 0.085,
            "pickup": true
          },
          {
            "rel": 2,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 4,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "B": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -5,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -5,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 0.75,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 15,
            "beats": 0.25,
            "vel": 0.085,
            "pickup": true
          },
          {
            "rel": -3,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "answer": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -1,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -2,
            "step": 8,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 14,
            "beats": 1,
            "vel": 0.085
          },
          {
            "rel": -2,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 20,
            "beats": 0.75,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      "tag": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.25,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 1,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -1,
            "step": 3,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 5,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 1,
            "step": 7,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 9,
            "beats": 1.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 15,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      }
    },
    "structureHint": "aaba",
    "score": 0.98,
    "bassPhrase": {
      "cells": [
        {
          "rel": 0,
          "step": 0,
          "beats": 1.5,
          "vel": 0.085,
          "accent": true
        },
        {
          "rel": -3,
          "step": 6,
          "beats": 1.5,
          "vel": 0.085
        },
        {
          "rel": 0,
          "step": 12,
          "beats": 3,
          "vel": 0.085,
          "accent": true
        }
      ]
    }
  },
  {
    "id": "mellow-waltzes1",
    "mood": "mellow",
    "source": "mined",
    "phrases": {
      "A": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 4,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 5,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 4,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 16,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 4,
            "step": 20,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      "B": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 4,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 16,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 22,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "answer": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 4,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -4,
            "step": 16,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      "tag": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 4,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 16,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    },
    "structureHint": "aaba",
    "score": 0.977,
    "bassPhrase": {
      "cells": [
        {
          "rel": 0,
          "step": 0,
          "beats": 2,
          "vel": 0.085,
          "accent": true
        },
        {
          "rel": -1,
          "step": 8,
          "beats": 1,
          "vel": 0.085,
          "accent": true
        },
        {
          "rel": 0,
          "step": 12,
          "beats": 3,
          "vel": 0.085,
          "accent": true
        }
      ]
    }
  },
  {
    "id": "mellow-waltzes10",
    "mood": "mellow",
    "source": "mined",
    "phrases": {
      "A": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 4,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 16,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 22,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "B": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 4,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 16,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 22,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "answer": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 4,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 12,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 20,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      "tag": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 4,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    },
    "structureHint": "call-response",
    "score": 0.973
  },
  {
    "id": "mellow-jigs101",
    "mood": "jazzy",
    "source": "mined",
    "phrases": {
      "A": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 5,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 4,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "B": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -1,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 1,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "answer": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -4,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 5,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 4,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "tag": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -5,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -4,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    },
    "structureHint": "aaba",
    "score": 0.941
  },
  {
    "id": "mellow-waltzes11",
    "mood": "mellow",
    "source": "mined",
    "phrases": {
      "A": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 4,
            "beats": 3,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 16,
            "beats": 3,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      "B": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 3,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 16,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 20,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      "answer": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 4,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -4,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 20,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      "tag": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 3,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 12,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 20,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    },
    "structureHint": "aaba",
    "score": 0.931
  },
  {
    "id": "mellow-ashover1",
    "mood": "jazzy",
    "source": "mined",
    "phrases": {
      "A": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 4,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -4,
            "step": 16,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 22,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "B": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 4,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -5,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 20,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      "answer": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -4,
            "step": 16,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -5,
            "step": 20,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      "tag": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 4,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 16,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    },
    "structureHint": "aaba",
    "score": 0.931
  },
  {
    "id": "mellow-jigs10",
    "mood": "rainy",
    "source": "mined",
    "phrases": {
      "A": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 2,
            "beats": 1,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -1,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "B": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 1,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "answer": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 6,
            "beats": 1,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 1,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 1,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 18,
            "beats": 1.5,
            "vel": 0.085
          }
        ]
      },
      "tag": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 12,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 18,
            "beats": 1,
            "vel": 0.085
          }
        ]
      }
    },
    "structureHint": "through-song",
    "score": 0.921
  },
  {
    "id": "mellow-jigs1",
    "mood": "rainy",
    "source": "mined",
    "phrases": {
      "A": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      "B": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 2,
            "beats": 1,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 14,
            "beats": 1,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "answer": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -5,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -4,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      "tag": {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 2,
            "beats": 1.5,
            "vel": 0.085
          },
          {
            "rel": 1,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    },
    "structureHint": "hook-develop",
    "score": 0.921
  }
];
