// AUTO-GENERATED by scripts/build-mined-library.ts — do not edit by hand.
// Phrase contours mined from the Nottingham folk-tune dataset (GPL-3.0) and
// abstracted into key-agnostic scale-step templates. Regenerate with:
//   npm run mine-melodies -- scripts/midi --out scripts/mined-all.json
//   npx tsx scripts/build-mined-library.ts

import type { PhraseTemplate } from "./melodies";

export const MINED_PHRASES: Record<
  "mellow" | "jazzy" | "rainy",
  Record<"A" | "B" | "answer" | "tag", PhraseTemplate[]>
> = {
  "mellow": {
    "A": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 4,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 5,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 4,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 16,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 4,
            "step": 20,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 4,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 16,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 4,
            "step": 20,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    ],
    "B": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 4,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 16,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 22,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 4,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 16,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    ],
    "answer": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -2,
            "step": 4,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -1,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -2,
            "step": 16,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 20,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.25,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 1,
            "beats": 0.25,
            "vel": 0.085,
            "pickup": true
          },
          {
            "rel": 2,
            "step": 3,
            "beats": 0.25,
            "vel": 0.085,
            "pickup": true
          },
          {
            "rel": 3,
            "step": 4,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 1,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 16,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 20,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    ],
    "tag": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 4,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 16,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 4,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -4,
            "step": 16,
            "beats": 2,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    ]
  },
  "jazzy": {
    "A": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 4,
            "beats": 0.75,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 7,
            "beats": 0.25,
            "vel": 0.085,
            "pickup": true
          },
          {
            "rel": 2,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 4,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 2,
            "beats": 0.75,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 5,
            "beats": 0.25,
            "vel": 0.085,
            "pickup": true
          },
          {
            "rel": -1,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -1,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 14,
            "beats": 1.5,
            "vel": 0.085
          }
        ]
      }
    ],
    "B": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -5,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -5,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 0.75,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 15,
            "beats": 0.25,
            "vel": 0.085,
            "pickup": true
          },
          {
            "rel": -3,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 6,
            "beats": 0.75,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 9,
            "beats": 0.25,
            "vel": 0.085,
            "pickup": true
          },
          {
            "rel": 2,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 2,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 4,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    ],
    "answer": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 4,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 5,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -5,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -5,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 0.75,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 15,
            "beats": 0.25,
            "vel": 0.085,
            "pickup": true
          },
          {
            "rel": -3,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      }
    ],
    "tag": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -7,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -7,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -2,
            "step": 12,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 18,
            "beats": 1,
            "vel": 0.085
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 4,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 5,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      }
    ]
  },
  "rainy": {
    "A": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 3,
            "step": 2,
            "beats": 1,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 8,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -1,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 4,
            "step": 18,
            "beats": 1,
            "vel": 0.085
          }
        ]
      }
    ],
    "B": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 1,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 2,
            "beats": 1,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -5,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -4,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -3,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -7,
            "step": 14,
            "beats": 1.5,
            "vel": 0.085
          },
          {
            "rel": -6,
            "step": 20,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          }
        ]
      }
    ],
    "answer": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 1,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 7,
            "step": 10,
            "beats": 1,
            "vel": 0.085
          },
          {
            "rel": 7,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 4,
            "step": 16,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 3,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 2,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 1,
            "step": 8,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 0,
            "step": 12,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      }
    ],
    "tag": [
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -2,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -1,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 0,
            "step": 6,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -4,
            "step": 8,
            "beats": 1.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -3,
            "step": 14,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -4,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -5,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      },
      {
        "cells": [
          {
            "rel": 0,
            "step": 0,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 2,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": -2,
            "step": 4,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 4,
            "step": 6,
            "beats": 1,
            "vel": 0.085
          },
          {
            "rel": 4,
            "step": 10,
            "beats": 0.5,
            "vel": 0.085
          },
          {
            "rel": 1,
            "step": 12,
            "beats": 1,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": 1,
            "step": 16,
            "beats": 0.5,
            "vel": 0.085,
            "accent": true
          },
          {
            "rel": -1,
            "step": 18,
            "beats": 0.5,
            "vel": 0.085
          }
        ]
      }
    ]
  }
};
