/**
 * build-mined-library — curate mined tune packages into a runtime module.
 *
 * Takes JSON from mine-melodies.ts (one complete package per source tune),
 * routes tunes to moods, folds wide leaps, and emits lib/audio/mined-tunes.ts.
 *
 * Usage: npx tsx scripts/build-mined-library.ts [mined.json]
 */

import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";
import type { MoodKey } from "../lib/audio/moods";
import type { StructureId } from "../lib/audio/melodies";
import { cleanTunePackage, type TunePackage } from "../lib/audio/tune-packages";

const MOODS: MoodKey[] = ["mellow", "jazzy", "rainy"];

/** Source file → mood routing. Expand as the MIDI corpus grows. */
const ROUTING: Record<MoodKey, string[]> = {
  mellow: ["waltzes1.mid", "waltzes10.mid", "waltzes11.mid"],
  jazzy: ["jigs100.mid", "jigs101.mid", "ashover1.mid"],
  rainy: ["jigs10.mid", "jigs1.mid"],
};

const MAX_PACKAGES_PER_MOOD = 5;
const MIN_SCORE = 0.4;

interface MinedJsonPackage {
  id: string;
  file: string;
  mood?: string;
  score: number;
  structureHint: StructureId;
  phrases: TunePackage["phrases"];
  bassPhrase?: TunePackage["bassPhrase"];
}

interface MinedJson {
  packages?: MinedJsonPackage[];
  /** Legacy format — ignored; re-run mine-melodies to upgrade. */
  tunes?: unknown[];
}

function main() {
  const inPath = process.argv[2] ?? "scripts/mined-all.json";
  const raw = JSON.parse(readFileSync(inPath, "utf8")) as MinedJson;

  if (!raw.packages?.length) {
    console.error(
      "No packages in input — re-run: npm run mine-melodies -- scripts/midi --out scripts/mined-all.json",
    );
    process.exit(1);
  }

  const byFile = new Map(raw.packages.map((p) => [basename(p.file), p]));
  const library: TunePackage[] = [];

  for (const mood of MOODS) {
    let kept = 0;
    for (const file of ROUTING[mood]) {
      if (kept >= MAX_PACKAGES_PER_MOOD) break;
      const mined = byFile.get(file);
      if (!mined) {
        console.error(`warning: routed tune not found: ${file}`);
        continue;
      }
      if (mined.score < MIN_SCORE) {
        console.error(`warning: low score ${mined.score} — skipping ${file}`);
        continue;
      }
      library.push(
        cleanTunePackage({
          id: mined.id,
          mood,
          source: "mined",
          phrases: mined.phrases,
          structureHint: mined.structureHint,
          score: mined.score,
          bassPhrase: mined.bassPhrase,
        }),
      );
      kept++;
    }
  }

  library.sort((a, b) => (b.score ?? 0) - (a.score ?? 0));

  const header = `// AUTO-GENERATED by scripts/build-mined-library.ts — do not edit by hand.
// Complete tune packages mined from folk MIDI (GPL-3.0). Regenerate with:
//   npm run mine-melodies -- scripts/midi --out scripts/mined-all.json
//   npx tsx scripts/build-mined-library.ts

import type { TunePackage } from "./tune-packages";

export const MINED_TUNE_PACKAGES: TunePackage[] = ${JSON.stringify(library, null, 2)};
`;

  const outPath = "lib/audio/mined-tunes.ts";
  writeFileSync(outPath, header);
  console.error(`wrote ${library.length} tune package(s) to ${outPath}`);
}

main();
