/**
 * build-mined-library — curate raw mined phrases into a ready-to-merge module.
 *
 * Takes the JSON emitted by mine-melodies.ts and:
 *   - routes each source tune to a mood (chosen from its detected key),
 *   - folds wide melodic leaps back into a single octave so they don't pile
 *     up against the scale edges when the engine clamps them,
 *   - keeps only the first `PER_PHRASE` templates per id per mood (lofi-sparse),
 *   - emits lib/audio/mined-phrases.ts exporting MINED_PHRASES.
 *
 * Usage: npx tsx scripts/build-mined-library.ts [mined.json]
 */

import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";
import type { PhraseTemplate } from "../lib/audio/melodies";

const PHRASE_IDS = ["A", "B", "answer", "tag"] as const;
type PhraseId = (typeof PHRASE_IDS)[number];
const MOODS = ["mellow", "jazzy", "rainy"] as const;
type MoodKey = (typeof MOODS)[number];

// Mood routing, chosen from the keys mine-melodies.ts detected:
//   waltzes (lyrical major) -> mellow, jigs/ashover (upbeat major) -> jazzy,
//   minor jigs -> rainy. Edit this map as the corpus grows.
const ROUTING: Record<MoodKey, string[]> = {
  mellow: ["waltzes1.mid", "waltzes10.mid", "waltzes11.mid"],
  jazzy: ["jigs100.mid", "jigs101.mid", "ashover1.mid"],
  rainy: ["jigs10.mid", "jigs1.mid"],
};

/** Templates to keep per phrase id per mood — matches the hand-authored size. */
const PER_PHRASE = 2;

interface MinedTune {
  file: string;
  phrases: Record<PhraseId, PhraseTemplate[]>;
}

/** Fold a diatonic-step offset back into roughly one octave (period 7). */
function foldRel(rel: number): number {
  while (rel > 7) rel -= 7;
  while (rel < -7) rel += 7;
  return rel;
}

function cleanTemplate(tpl: PhraseTemplate): PhraseTemplate {
  return { cells: tpl.cells.map((c) => ({ ...c, rel: foldRel(c.rel) })) };
}

function main() {
  const inPath = process.argv[2] ?? "scripts/mined-all.json";
  const data = JSON.parse(readFileSync(inPath, "utf8")) as { tunes: MinedTune[] };
  const byFile = new Map(data.tunes.map((t) => [basename(t.file), t]));

  const library: Record<MoodKey, Record<PhraseId, PhraseTemplate[]>> = {
    mellow: { A: [], B: [], answer: [], tag: [] },
    jazzy: { A: [], B: [], answer: [], tag: [] },
    rainy: { A: [], B: [], answer: [], tag: [] },
  };

  for (const mood of MOODS) {
    for (const id of PHRASE_IDS) {
      for (const file of ROUTING[mood]) {
        const tune = byFile.get(file);
        if (!tune) {
          console.error(`warning: routed tune not found in input: ${file}`);
          continue;
        }
        for (const tpl of tune.phrases[id]) {
          if (library[mood][id].length >= PER_PHRASE) break;
          library[mood][id].push(cleanTemplate(tpl));
        }
        if (library[mood][id].length >= PER_PHRASE) break;
      }
    }
  }

  const header = `// AUTO-GENERATED by scripts/build-mined-library.ts — do not edit by hand.
// Phrase contours mined from the Nottingham folk-tune dataset (GPL-3.0) and
// abstracted into key-agnostic scale-step templates. Regenerate with:
//   npm run mine-melodies -- scripts/midi --out scripts/mined-all.json
//   npx tsx scripts/build-mined-library.ts

import type { PhraseTemplate } from "./melodies";

export const MINED_PHRASES: Record<
  "mellow" | "jazzy" | "rainy",
  Record<"A" | "B" | "answer" | "tag", PhraseTemplate[]>
> = ${JSON.stringify(library, null, 2)};
`;

  const outPath = "lib/audio/mined-phrases.ts";
  writeFileSync(outPath, header);
  const total = MOODS.reduce(
    (s, m) => s + PHRASE_IDS.reduce((n, id) => n + library[m][id].length, 0),
    0,
  );
  console.error(`wrote ${total} curated phrases to ${outPath}`);
}

main();
