/**
 * generate-sample-catalog — scan public/samples and emit a typed catalog.
 *
 * Skips *-drums packs (wired separately later). Detects layout from filenames.
 *
 * Usage:
 *   npx tsx scripts/generate-sample-catalog.ts
 *
 * Writes lib/audio/instruments/catalog.ts
 */

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { parseSampleFile } from "../lib/audio/parse-sample-file";
import type { SampleLayout, SamplePackCatalog, SampleZoneEntry } from "../lib/audio/sample-types";

const SAMPLES_ROOT = resolve("public/samples");
const OUT_PATH = resolve("lib/audio/instruments/catalog.ts");

const SKIP_PACKS = new Set(["acoustic-drums", "orchestral-drums"]);

/** Default octave when a pack only has pitch-class filenames (e.g. electric-bass/A.flac). */
const PACK_DEFAULT_OCTAVE: Record<string, number> = {
  "electric-bass": 2,
};

const LAYER_WEIGHTS: Record<string, Record<string, number>> = {
  "velocity-layers": { L: 0.38, H: 0.72 },
  "dynamic-layers": { f: 0.35, mp: 0.45, mf: 0.62, ff: 0.78 },
};

function detectLayout(layerKeys: Set<string>, maxFilesPerZone: number): SampleLayout {
  if (layerKeys.has("L") && layerKeys.has("H")) return "velocity-layers";
  if ([...layerKeys].every((k) => /^\d+$/.test(k))) return "velocity-steps";
  if ([...layerKeys].some((k) => ["f", "mf", "mp", "ff"].includes(k))) return "dynamic-layers";
  if (maxFilesPerZone > 1) return "round-robin";
  return "single";
}

function buildPack(id: string): SamplePackCatalog | null {
  const dir = join(SAMPLES_ROOT, id);
  let files: string[];
  try {
    files = readdirSync(dir).filter((f) => /\.(wav|flac|ogg)$/i.test(f));
  } catch {
    return null;
  }
  if (files.length === 0) return null;

  const defaultOctave = PACK_DEFAULT_OCTAVE[id] ?? 3;
  const zoneMap = new Map<number, SampleZoneEntry>();
  const layerKeys = new Set<string>();
  let maxFilesPerZone = 0;

  for (const file of files) {
    const parsed = parseSampleFile(file, { defaultOctave, skipIntervals: true });
    if (!parsed) continue;

    layerKeys.add(parsed.layer);
    let zone = zoneMap.get(parsed.rootMidi);
    if (!zone) {
      zone = { rootNote: parsed.rootNote, rootMidi: parsed.rootMidi, layers: {} };
      zoneMap.set(parsed.rootMidi, zone);
    }
    const pool = zone.layers[parsed.layer] ?? [];
    pool.push(parsed.file);
    zone.layers[parsed.layer] = pool;
  }

  const zones = [...zoneMap.values()].sort((a, b) => a.rootMidi - b.rootMidi);
  if (zones.length === 0) return null;

  for (const z of zones) {
    const count = Object.values(z.layers).reduce((n, arr) => n + arr.length, 0);
    maxFilesPerZone = Math.max(maxFilesPerZone, count);
  }

  const layout = detectLayout(layerKeys, maxFilesPerZone);

  let layerWeights = LAYER_WEIGHTS[layout];
  if (layout === "velocity-steps") {
    layerWeights = {};
    for (const key of layerKeys) {
      const n = parseInt(key, 10);
      if (!Number.isNaN(n)) layerWeights[key] = Math.min(1, n / 127);
    }
  }

  return {
    id,
    basePath: `/samples/${id}`,
    layout,
    layerWeights,
    zones,
    fileCount: files.length,
  };
}

function main() {
  const packIds = readdirSync(SAMPLES_ROOT)
    .filter((name) => {
      if (SKIP_PACKS.has(name)) return false;
      try {
        return statSync(join(SAMPLES_ROOT, name)).isDirectory();
      } catch {
        return false;
      }
    })
    .sort();

  const packs = packIds.map(buildPack).filter((p): p is SamplePackCatalog => p !== null);

  const body = `// Auto-generated by scripts/generate-sample-catalog.ts — do not edit by hand.
// Re-run: npm run generate-samples

import type { SampleCatalog } from "../sample-types";

export const SAMPLE_CATALOG: SampleCatalog = ${JSON.stringify({ generatedAt: new Date().toISOString(), packs }, null, 2)};

export const SAMPLE_PACKS = Object.fromEntries(
  SAMPLE_CATALOG.packs.map((p) => [p.id, p]),
) as Record<string, (typeof SAMPLE_CATALOG.packs)[number]>;
`;

  writeFileSync(OUT_PATH, body);
  for (const p of packs) {
    console.log(`  ${p.id}: ${p.zones.length} zones, ${p.fileCount} files (${p.layout})`);
  }
  console.log(`Wrote ${packs.length} packs → ${OUT_PATH}`);
}

main();
