/**
 * generate-drum-catalog — scan drum packs and emit pool-based catalog.
 *
 *   acoustic-drums/{PoolName}/{n}-{PoolName}.flac
 *   (orchestral-drums omitted — acoustic only)
 *
 * Usage: npx tsx scripts/generate-drum-catalog.ts
 */

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { DrumCatalog, DrumPackCatalog, DrumPool } from "../lib/audio/drum-types";

const SAMPLES_ROOT = resolve("public/samples");
const OUT_PATH = resolve("lib/audio/instruments/drum-catalog.ts");

function buildAcousticPack(id: string): DrumPackCatalog | null {
  const dir = join(SAMPLES_ROOT, id);
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return null;
  }

  const pools: DrumPool[] = [];
  let fileCount = 0;

  for (const name of entries.sort()) {
    const sub = join(dir, name);
    if (!statSync(sub).isDirectory()) continue;
    const files = readdirSync(sub)
      .filter((f) => /\.(wav|flac|ogg)$/i.test(f))
      .sort((a, b) => {
        const na = parseInt(a, 10);
        const nb = parseInt(b, 10);
        if (!Number.isNaN(na) && !Number.isNaN(nb)) return na - nb;
        return a.localeCompare(b);
      })
      .map((f) => `${name}/${f}`);
    if (files.length === 0) continue;
    pools.push({ id: name, files });
    fileCount += files.length;
  }

  if (pools.length === 0) return null;
  return { id, basePath: `/samples/${id}`, pools, fileCount };
}

function main() {
  const catalog: DrumCatalog = {
    generatedAt: new Date().toISOString(),
    packs: [],
  };

  const acoustic = buildAcousticPack("acoustic-drums");
  if (acoustic) catalog.packs.push(acoustic);

  const body = `// Auto-generated by scripts/generate-drum-catalog.ts — do not edit by hand.
// Re-run: npm run generate-samples

import type { DrumCatalog } from "../drum-types";

export const DRUM_CATALOG: DrumCatalog = ${JSON.stringify(catalog, null, 2)};

export const DRUM_PACKS = Object.fromEntries(
  DRUM_CATALOG.packs.map((p) => [p.id, p]),
) as Record<string, (typeof DRUM_CATALOG.packs)[number]>;
`;

  writeFileSync(OUT_PATH, body);
  for (const p of catalog.packs) {
    console.log(`  ${p.id}: ${p.pools.length} pools, ${p.fileCount} files`);
  }
  console.log(`Wrote drum catalog → ${OUT_PATH}`);
}

main();
