// Auto-generated by scripts/generate-sample-catalog.ts — do not edit by hand.
// Re-run: npm run generate-samples

import type { SampleCatalog } from "../sample-types";

export const SAMPLE_CATALOG: SampleCatalog = {
  "generatedAt": "2026-06-29T05:24:48.674Z",
  "packs": [
    {
      "id": "piano",
      "basePath": "/samples/piano",
      "layout": "velocity-layers",
      "layerWeights": {
        "L": 0.38,
        "H": 0.72
      },
      "zones": [
        {
          "rootNote": "A0",
          "rootMidi": 21,
          "layers": {
            "H": [
              "A0vH.wav"
            ],
            "L": [
              "A0vL.wav"
            ]
          }
        },
        {
          "rootNote": "B0",
          "rootMidi": 23,
          "layers": {
            "H": [
              "B0vH.wav"
            ]
          }
        },
        {
          "rootNote": "C1",
          "rootMidi": 24,
          "layers": {
            "H": [
              "C1vH.wav"
            ],
            "L": [
              "C1vL.wav"
            ]
          }
        },
        {
          "rootNote": "D#1",
          "rootMidi": 27,
          "layers": {
            "H": [
              "D#1vH.wav"
            ],
            "L": [
              "D#1vL.wav"
            ]
          }
        },
        {
          "rootNote": "F#1",
          "rootMidi": 30,
          "layers": {
            "H": [
              "F#1vH.wav"
            ],
            "L": [
              "F#1vL.wav"
            ]
          }
        },
        {
          "rootNote": "A1",
          "rootMidi": 33,
          "layers": {
            "H": [
              "A1vH.wav"
            ],
            "L": [
              "A1vL.wav"
            ]
          }
        },
        {
          "rootNote": "B1",
          "rootMidi": 35,
          "layers": {
            "H": [
              "B1vH.wav"
            ]
          }
        },
        {
          "rootNote": "C2",
          "rootMidi": 36,
          "layers": {
            "H": [
              "C2vH.wav"
            ],
            "L": [
              "C2vL.wav"
            ]
          }
        },
        {
          "rootNote": "D#2",
          "rootMidi": 39,
          "layers": {
            "H": [
              "D#2vH.wav"
            ],
            "L": [
              "D#2vL.wav"
            ]
          }
        },
        {
          "rootNote": "F#2",
          "rootMidi": 42,
          "layers": {
            "H": [
              "F#2vH.wav"
            ],
            "L": [
              "F#2vL.wav"
            ]
          }
        },
        {
          "rootNote": "A2",
          "rootMidi": 45,
          "layers": {
            "L": [
              "A2vL.wav"
            ]
          }
        },
        {
          "rootNote": "B2",
          "rootMidi": 47,
          "layers": {
            "H": [
              "B2vH.wav"
            ]
          }
        },
        {
          "rootNote": "C3",
          "rootMidi": 48,
          "layers": {
            "H": [
              "C3vH.wav"
            ],
            "L": [
              "C3vL.wav"
            ]
          }
        },
        {
          "rootNote": "D#3",
          "rootMidi": 51,
          "layers": {
            "H": [
              "D#3vH.wav"
            ],
            "L": [
              "D#3vL.wav"
            ]
          }
        },
        {
          "rootNote": "F#3",
          "rootMidi": 54,
          "layers": {
            "H": [
              "F#3vH.wav"
            ],
            "L": [
              "F#3vL.wav"
            ]
          }
        },
        {
          "rootNote": "A3",
          "rootMidi": 57,
          "layers": {
            "H": [
              "A3vH.wav"
            ],
            "L": [
              "A3vL.wav"
            ]
          }
        },
        {
          "rootNote": "B3",
          "rootMidi": 59,
          "layers": {
            "H": [
              "B3vH.wav"
            ]
          }
        },
        {
          "rootNote": "C4",
          "rootMidi": 60,
          "layers": {
            "L": [
              "C4vL.wav"
            ]
          }
        },
        {
          "rootNote": "D#4",
          "rootMidi": 63,
          "layers": {
            "H": [
              "D#4vH.wav"
            ],
            "L": [
              "D#4vL.wav"
            ]
          }
        },
        {
          "rootNote": "F#4",
          "rootMidi": 66,
          "layers": {
            "H": [
              "F#4vH.wav"
            ],
            "L": [
              "F#4vL.wav"
            ]
          }
        },
        {
          "rootNote": "A4",
          "rootMidi": 69,
          "layers": {
            "H": [
              "A4vH.wav"
            ],
            "L": [
              "A4vL.wav"
            ]
          }
        },
        {
          "rootNote": "B4",
          "rootMidi": 71,
          "layers": {
            "H": [
              "B4vH.wav"
            ]
          }
        },
        {
          "rootNote": "C5",
          "rootMidi": 72,
          "layers": {
            "H": [
              "C5vH.wav"
            ],
            "L": [
              "C5vL.wav"
            ]
          }
        },
        {
          "rootNote": "D#5",
          "rootMidi": 75,
          "layers": {
            "H": [
              "D#5vH.wav"
            ],
            "L": [
              "D#5vL.wav"
            ]
          }
        },
        {
          "rootNote": "F#5",
          "rootMidi": 78,
          "layers": {
            "H": [
              "F#5vH.wav"
            ],
            "L": [
              "F#5vL.wav"
            ]
          }
        },
        {
          "rootNote": "A5",
          "rootMidi": 81,
          "layers": {
            "H": [
              "A5vH.wav"
            ],
            "L": [
              "A5vL.wav"
            ]
          }
        },
        {
          "rootNote": "B5",
          "rootMidi": 83,
          "layers": {
            "H": [
              "B5vH.wav"
            ]
          }
        },
        {
          "rootNote": "C6",
          "rootMidi": 84,
          "layers": {
            "H": [
              "C6vH.wav"
            ],
            "L": [
              "C6vL.wav"
            ]
          }
        },
        {
          "rootNote": "D#6",
          "rootMidi": 87,
          "layers": {
            "H": [
              "D#6vH.wav"
            ],
            "L": [
              "D#6vL.wav"
            ]
          }
        },
        {
          "rootNote": "F#6",
          "rootMidi": 90,
          "layers": {
            "H": [
              "F#6vH.wav"
            ],
            "L": [
              "F#6vL.wav"
            ]
          }
        },
        {
          "rootNote": "A6",
          "rootMidi": 93,
          "layers": {
            "H": [
              "A6vH.wav"
            ],
            "L": [
              "A6vL.wav"
            ]
          }
        },
        {
          "rootNote": "B6",
          "rootMidi": 95,
          "layers": {
            "H": [
              "B6vH.wav"
            ]
          }
        },
        {
          "rootNote": "C7",
          "rootMidi": 96,
          "layers": {
            "H": [
              "C7vH.wav"
            ],
            "L": [
              "C7vL.wav"
            ]
          }
        },
        {
          "rootNote": "D#7",
          "rootMidi": 99,
          "layers": {
            "H": [
              "D#7vH.wav"
            ],
            "L": [
              "D#7vL.wav"
            ]
          }
        },
        {
          "rootNote": "F#7",
          "rootMidi": 102,
          "layers": {
            "H": [
              "F#7vH.wav"
            ],
            "L": [
              "F#7vL.wav"
            ]
          }
        },
        {
          "rootNote": "A7",
          "rootMidi": 105,
          "layers": {
            "H": [
              "A7vH.wav"
            ],
            "L": [
              "A7vL.wav"
            ]
          }
        },
        {
          "rootNote": "B7",
          "rootMidi": 107,
          "layers": {
            "H": [
              "B7vH.wav"
            ]
          }
        },
        {
          "rootNote": "C8",
          "rootMidi": 108,
          "layers": {
            "H": [
              "C8vH.wav"
            ],
            "L": [
              "C8vL.wav"
            ]
          }
        }
      ],
      "fileCount": 66
    }
  ]
};

export const SAMPLE_PACKS = Object.fromEntries(
  SAMPLE_CATALOG.packs.map((p) => [p.id, p]),
) as Record<string, (typeof SAMPLE_CATALOG.packs)[number]>;
