// Auto-generated by scripts/generate-drum-catalog.ts — do not edit by hand.
// Re-run: npm run generate-samples

import type { DrumCatalog } from "../drum-types";

export const DRUM_CATALOG: DrumCatalog = {
  "generatedAt": "2026-06-29T05:24:48.985Z",
  "packs": []
};

export const DRUM_PACKS = Object.fromEntries(
  DRUM_CATALOG.packs.map((p) => [p.id, p]),
) as Record<string, (typeof DRUM_CATALOG.packs)[number]>;
